name: Bug/Problem report
description: Create a report to help us improve Autocaliweb
title: "[BUG] "
labels: ["bug", "triage"]
projects: ["gelbphoenix/2"]
body:
  - type: markdown
    attributes:
      value: |
        Please have a look at our [Contributing Guidelines](https://github.com/gelbphoenix/autocaliweb/blob/main/CONTRIBUTING.md)

        Make sure that you are submitting a new bug that was not previously reported or already fixed.
  - type: textarea
    id: bug-description
    attributes:
      label: Description of the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: What does it take to reproduce the behaviour?
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: If applicable, provide relevant log output. No need for backticks here.
      render: shell
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which operating system do you use? Please provide the version as well.
      placeholder: Raspberry Pi OS
    validations:
      required: true
  - type: input
    id: acw-version
    attributes:
      label: Autocaliweb version
      description: What is the Autocaliweb version your reporting this for? (Either version number or commit sha1 [with git rev-parse --short HEAD])
      placeholder: Autocaliweb ...
    validations:
      required: true
  - type: input
    id: hardware
    attributes:
      label: Hardware
      description: On what Hardware is this behaviour?
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      description: What browser do you use? Please write both the Browser and it's version.
      placeholder: Firefox 147.0.1
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: |
        Add any other context about the problem here. [e.g. access via reverse proxy, database background sync, special database location]

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
